export const DARKMODE_ON = "DARKMODE_ON";
export const DARKMODE_OFF = "DARKMODE_OFF";

export const GETHEADPHONES_SUCCESS = "GETHEADPHONES_SUCCESS";
export const GETHEADPHONES_FAIL = "GETHEADPHONES_FAIL";

export const CLEARHPERRORS = "CLEARHPERRORS";
